before_script:
    - composer update

stages:
    - test

phpunit:
    stage: test
    script:
        - php -d zend_extension=xdebug.so ./vendor/bin/phpunit -c phpunit.xml --coverage-text --colors=never
